# Generated by Django 5.1.5 on 2025-02-06 13:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('trackerapp', '0002_user_username_alter_user_password'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='full_name',
        ),
    ]
