# Generated by Django 5.1.5 on 2025-02-10 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trackerapp', '0005_alter_user_username_document'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='document',
            name='is_read',
        ),
        migrations.RemoveField(
            model_name='document',
            name='timestamp',
        ),
        migrations.AddField(
            model_name='document',
            name='received',
            field=models.BooleanField(default=False),
        ),
    ]
