# Generated by Django 5.1.5 on 2025-02-10 12:56

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trackerapp', '0006_remove_document_is_read_remove_document_timestamp_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='document',
            name='received',
        ),
        migrations.AddField(
            model_name='document',
            name='is_read',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='document',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
