# Generated by Django 5.1.5 on 2025-02-10 13:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('trackerapp', '0007_remove_document_received_document_is_read_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='document',
            name='is_read',
        ),
        migrations.RemoveField(
            model_name='document',
            name='is_urgent',
        ),
        migrations.RemoveField(
            model_name='document',
            name='timestamp',
        ),
    ]
