# Generated by Django 5.1.5 on 2025-02-12 18:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trackerapp', '0009_document_is_read_document_is_urgent_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='is_received',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='document',
            name='is_sent',
            field=models.BooleanField(default=False),
        ),
    ]
